version: '3'
services:
  web:
    build: .
    ports:
      - "5000:8080"
  db:
    image: anidb
    environment:
      DB_USER: root
      DB_PASSWORD: root
      DB_URL:  jdbc:mysql://localhost:3306/trainingdb